BeerTracker5000/Models/Beer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BeerTracker5000.Models
{
    // Beer Data Model Class --- Defines properties of data stored in database
    // Use [Display] to set the display name of the property in the View
    public class Beer
    {
        public int ID { get; set; }
        [Display(Name = "Beer Name")]
        public string BeerName { get; set; }
        [Display(Name = "Brewery Name")]
        public string BreweryName { get; set; }
        public string Style { get; set; }
        public decimal Abv { get; set; }
        public int Ibu { get; set; }
        public int Rating { get; set; }
        public string Notes { get; set; }
    }
}

BeerTracker5000/Controllers/BeersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BeerTracker5000.Models;

namespace BeerTracker5000.Controllers
{
    //Beer Controllers  ----  Coordinates URL requests, retrieve data, and call view templates for the CRUD portion of App
    public class BeersController : Controller
    {
        private readonly BeerTracker5000Context _context;

        public BeersController(BeerTracker5000Context context)
        {
            _context = context;    
        }

        // GET: Beers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Beer.ToListAsync());
        }

        // GET: Beers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer
                .SingleOrDefaultAsync(m => m.ID == id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // GET: Beers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Beers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,BeerName,BreweryName,Style,Abv,Ibu,Rating,Notes")] Beer beer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(beer);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(beer);
        }

        // GET: Beers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer.SingleOrDefaultAsync(m => m.ID == id);
            if (beer == null)
            {
                return NotFound();
            }
            return View(beer);
        }

        // POST: Beers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,BeerName,BreweryName,Style,Abv,Ibu,Rating,Notes")] Beer beer)
        {
            if (id != beer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(beer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BeerExists(beer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(beer);
        }

        // GET: Beers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var beer = await _context.Beer
                .SingleOrDefaultAsync(m => m.ID == id);
            if (beer == null)
            {
                return NotFound();
            }

            return View(beer);
        }

        // POST: Beers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var beer = await _context.Beer.SingleOrDefaultAsync(m => m.ID == id);
            _context.Beer.Remove(beer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool BeerExists(int id)
        {
            return _context.Beer.Any(e => e.ID == id);
        }
    }
}

BeerTracker5000/Controllers/HelloWorldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

/*namespace BeerTracker5000.Controllers
{
    public class HelloWorldController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Welcome(string name, int numTimes = 1)
        {
            ViewData["Message"] = "Hello " + name;
            ViewData["numTimes"] = numTimes;

            return View();
        }
    }
}*/

BeerTracker5000/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BeerTracker5000.Controllers
{
    // Home page controller

    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            //ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            //ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

BeerTracker5000/Views/Beers/Create.cshtml
@model BeerTracker5000.Models.Beer

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-group-sm">
        <h4>Beer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="BeerName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BeerName" class="form-control" />
                <span asp-validation-for="BeerName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BreweryName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BreweryName" class="form-control" />
                <span asp-validation-for="BreweryName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Style" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Style" class="form-control" />
                <span asp-validation-for="Style" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Abv" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Abv" class="form-control" />
                <span asp-validation-for="Abv" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Ibu" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Ibu" class="form-control" />
                <span asp-validation-for="Ibu" class="text-danger"></span>
            </div>
        </div>
        @*<div class="form-group">
            <label asp-for="Rating" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
        </div>*@
        <div class="form-group">
            <label asp-for="Notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeerTracker5000/Views/Beers/Delete.cshtml
@model BeerTracker5000.Models.Beer

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete this beer!</h2>

<h3>What did this beer do to deserve this fate? Are you sure you want to delete it?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.BeerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BeerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BreweryName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BreweryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Abv)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Abv)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ibu)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ibu)
        </dd>
        @*<dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

BeerTracker5000/Views/Beers/Details.cshtml
@model BeerTracker5000.Models.Beer

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Beer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BeerName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BeerName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BreweryName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BreweryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Style)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Style)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Abv)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Abv)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ibu)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ibu)
        </dd>
        @*<dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BeerTracker5000/Views/Beers/Edit.cshtml
@model BeerTracker5000.Models.Beer

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Beer</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="BeerName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BeerName" class="form-control" />
                <span asp-validation-for="BeerName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BreweryName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BreweryName" class="form-control" />
                <span asp-validation-for="BreweryName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Style" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Style" class="form-control" />
                <span asp-validation-for="Style" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Abv" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Abv" class="form-control" />
                <span asp-validation-for="Abv" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Ibu" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Ibu" class="form-control" />
                <span asp-validation-for="Ibu" class="text-danger"></span>
            </div>
        </div>
        @*<div class="form-group">
            <label asp-for="Rating" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
        </div>*@
        <div class="form-group">
            <label asp-for="Notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BeerTracker5000/Views/Beers/Index.cshtml
@model IEnumerable<BeerTracker5000.Models.Beer>

@{
    ViewData["Title"] = "Index";
}

<h2>My Beers!</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table-condensed">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BeerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BreweryName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Style)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Abv)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ibu)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.Rating)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Notes)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BeerName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BreweryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Style)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Abv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ibu)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Notes)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

BeerTracker5000/Views/HelloWorld/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Beer List";
}

<h2>My Beer List</h2>

<p>Hello from our View Template!</p>

BeerTracker5000/Views/HelloWorld/Welcome.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

BeerTracker5000/Views/Home/About.cshtml
@{
    //ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<h1>About the Beer Tracker 5000</h1>

<h3>
    Built by a junior developer that often found himself considering a beer on the beer list and thinking to himself, "I've had 
    this beer before but I had a lot of other beers that night and I can't quite remember the finer details. I wish I had a convenient way
    to document my thoughts on a beer while I'm drinking it."
</h3>

<h3>
    The Beer Tracker 5000...because you may not remember all of the important details of the first (or second or third) beers of the night.
</h3>

BeerTracker5000/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>Have questions about the Beer Tracker 5000, feel free to contact me:</h2>
<h3>tdalhoff@live.com</h3>
<h3><a href="http://www.travis-dalhoff.com">www.travis-dalhoff.com</a></h3>

BeerTracker5000/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron text-center">
    <h1>BEER TRACKER 5000</h1>
</div>

<div class="row">
    <div class="col-md-4">
        <img src="~/images/Glass-of-Beer-28.png" style="width:200px; height: 250px;" class="img-responsive center-block" />
    </div>

    <div class="text-center col-md-4">
        <h2><a asp-area="" asp-controller="Beers" asp-action="Index">View, Add, Edit, and Delete your beers here!</a></h2>
    </div>

    <div class="col-md-4">
        <img src="~/images/Glass-of-Beer-28.png" style="width:200px; height: 250px;" class="img-responsive center-block" />
    </div>
</div>

BeerTracker5000/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeerTracker5000</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - BeerTracker5000</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>